class LaunchFileMaker:
    def __init__(self):
        self.rate = 300.0
        self.resolution = (1920, 1080)
        self.launch_file = """
<!--Autogenerated file-->
<launch>
    <!-- Configurable arguments -->
    <arg name="robot_name" default="sparus2"/>
    <arg name="enable_keyboard" default="true"/>
    <arg name="enable_joystick" default="true"/>
    <arg name="joystick_device" default="/dev/input/js0"/>
    <arg name="enable_gui" default="true"/>
    <arg name="enable_rviz" default="true"/>
    <arg name="is_simulation" default="true"/>
    
    

    <!-- Run Simulator -->
    <include file="$(find stonefish_ros)/launch/simulator.launch">
        <arg name="simulation_data" value="$(find cola2_stonefish)/data"/>
        <arg name="scenario_description" value="$(find stonefish_scene_generator)/scenarios/sparus2_haifa_deepersense.scn"/>
        <arg name="simulation_rate" value="{}"/>
        <arg name="graphics_resolution" value="{} {}"/>
        <arg name="graphics_quality" value="high"/>
    </include>
    
    <!-- RViz -->
    <group if="$(arg enable_rviz)">
        <node pkg="rviz" type="rviz" name="rviz" args="-d $(find cola2_sparus2)/scene/sparus2.rviz"/>
    </group>



    <node pkg="rosbag" type="record" name="rosbag_record_cam"
       args="record -o /home/zeged/bags/test.bag /camera2/image_raw/camera_info /camera2/image_raw/image_color /image_depth2/camera_info /image_depth2/image_depth /sparus2/Blue_view_M900_FLS2/display /sparus2/Blue_view_M900_FLS3/display /sparus2/Blue_view_M900_FLS4/display"
        />



</launch>

                    """.format(self.rate, self.resolution[0], self.resolution[1])




def main():
    maker = LaunchFileMaker()
    launch_file_path = '/home/zeged/catkin_ws/src/stonefish_scene_generator/launch/test.launch'
    f = open(launch_file_path, "w")
    f.write(maker.launch_file)
    f.close()

if __name__=="__main__":
    main()